# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Autism' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Autism
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'ReachabilitySwift', '~> 3'
  pod 'FBSDKLoginKit'
  pod 'GoogleSignIn'
  pod 'SDWebImage', '~> 5.0'
  pod 'SwiftyGif'
  pod 'Sketch'
  pod 'FLAnimatedImage'
  pod 'VariousViewsEffects'
  pod 'Firebase/Core'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Messaging'
  pod 'Crashlytics'
  pod 'Starscream'
  target 'AutismTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AutismUITests' do
    # Pods for testing
  end

end
